const place = [
    {
        "name": "Pyramid",
        "Introduction": "A pyramid is a structure whose outer surfaces are triangular and converge to a single step at the top, making the shape roughly a pyramid in the geometric sense.",
        "History": "The ancient Egyptians built pyramids from 2700 BC until around 1700 BC. The first pyramid was erected during the Third Dynasty by the Pharaoh Djoser and his architect Imhotep.",
        "Structure": "pyramid has at least three outer triangular surfaces (at least four faces including the base). The square pyramid, with a square base and four triangular outer surfaces, is a common version.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Pyramid",
        "Google-map": "https://goo.gl/maps/MXcXSHoqhjTHrF4MA",
    },
    {
        "name": "Christ Redeemer",
        "Introduction": "Christ the Redeemer (Portuguese: Cristo Redentor) is an Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil.",
        "History": "A symbol of Christianity around the world, the statue has also become a cultural icon of both Rio de Janeiro and Brazil and was voted one of the New Seven Wonders of the World.",
        "Structure": "Constructed between 1922 and 1931, the statue is 30 metres (98 ft) high, excluding its 8-metre (26 ft) pedestal. The arms stretch 28 metres (92 ft) wide. It is made of reinforced concrete and soapstone.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)",
        "Google-map": "https://goo.gl/maps/Xp2A7R3LZPysDuF78",
    },
    {
        "name": "Great wall of china",
        "Introduction": "The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. ",
        "History": "It was built by Qin Shi Huang in 214 BC during the Qin Dynasty to intercept the invasion of northern nomads. Although it is generally believed that the Great Wall was built by the first emperor, it was actually rebuilt and relocated by several dynasties, and most of the existing Great Wall was built during the Ming Dynasty.",
        "Structure": "10,051 wall sections, 1,764 ramparts or trenches, 29,510 individual buildings, and 2,211 fortifications or passes, with the walls and trenches spanning a total length of 21,196.18 km (13,170.70 mi).",
        "Wikipedia": "https://en.wikipedia.org/wiki/Great_Wall_of_China",
        "Google-map": "https://goo.gl/maps/eusBTmfngY8NXfYH7",
    },
    {
        "name": "Machu Picchu",
        "Introduction": "Machu Picchu is a 15th-century Inca citadel located in the Eastern Cordillera of southern Peru on a 2,430-meter (7,970 ft) mountain ridge. ",
        "History": "Machu Picchu was believed to have been built in the 1450s.  but 2021 study led  used radiocarbon dating to reveal that Machu Picchu may have been occupied from around 1420-1530 AD.",
        "Structure": "Machu Picchu was built in the classical Inca style, with polished dry-stone walls. Its three primary structures are the Intihuatana, the Temple of the Sun, and the Room of the Three Windows. Most of the outlying buildings have been reconstructed in order to give visitors a better idea of how they originally appeared.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Machu_Picchu",
        "Google-map": "https://goo.gl/maps/EC7T9XWuZX3G1n2E7",
    },
    {
        "name": "Petra",
        "Introduction": "Petra is an archaeological site in Jordan. It is located in a valley between the Dead Sea and the Gulf of Aqaba. It is located about 80 km south of the Dead Sea. Means cliff in Greek. ",
        "History": "The Edomites are believed to have lived near Petra from around 1200 BC. Excavations began at the beginning of the 20th century. As of 2014, 85% are said to be unexcavated.",
        "Structure": "It was built by carving out a steep rock wall, and is characterized by the many buildings and sculptures that show the fusion of ancient Eastern culture and Hellenistic culture.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Petra",
        "Google-map": "https://goo.gl/maps/JWHfMBmUmYTYjLFD7",
    },
    {
        "name": "Colosseum",
        "Introduction": "The Colosseum is an elliptical amphitheatre in the centre of the city of Rome, Italy, just east of the Roman Forum. ",
        "History": "An amphitheatre was built as a centerpiece of entertainment to appease the citizens while adopting an austerity policy. Today, it remains a symbol of ancient Rome as a tourist destination.",
        "Structure": "An elliptical shape with a length of 188m. The capacity is 80,000 people. The structure of the basement, the arena and the auditorium.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Colosseum",
        "Google-map": "https://goo.gl/maps/VzxnKfX81tNupubP6",
    },
    {
        "name": "Taj Mahal",
        "Introduction": "The Taj Mahal is an Islamic ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra.",
        "History": "It is believed that the mausoleum was once completed in 1643, continued construction for the next ten years, and was finally completed in its entirety in 1653.",
        "Structure": "TIt is made of white marble with the best of decorative art, and in front of it is a long, narrow pond with a fountain and an Islamic garden.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Taj_Mahal",
        "Google-map": "https://goo.gl/maps/kcnm3DJPeXS2duLs6",
    },
    {
        "name": "Chichen Itza",
        "Introduction": "Chichen Itza was a large pre-Columbian city built by the Maya people of the Terminal Classic period.",
        "History": "The Chichen Itza ruins belong to the southern area, which belongs to the 'Old Chichen Itza' built around the 6th century, and the 'New Chichen Itza' which incorporates the culture of the Maya Toltec civilization built after the 10th century. It is divided into two areas, the north area.",
        "Structure": "In the evening of the vernal and autumnal equinoxes, the stepped temple pyramid 'Temple of Kukulkan' creates a snake-like zigzag shadow on the stairs.",
        "Wikipedia": "https://en.wikipedia.org/wiki/Chichen_Itza",
        "Google-map": "https://goo.gl/maps/u7vJCnUd98UbcgRw9",
    },
]